### ISSUE TITLE
Cannot install in Hassio on RP3 + HASSOS 64 bits

### ISSUE THREAD

**Issue by Costash67** [yllibed/Zigbee2MqttAssistant#14]
Sorry, but i cannot install your addon.
This is the message i get in log:
19-08-24 08:57:30 ERROR (SyncWorker_3) [hassio.docker.interface] Can't install carldebilly/zigbee2mqttassistant:0.2.0-dev.58 -> 404 Client Error: Not Found ("no such image: carldebilly/zigbee2mqttassistant:0.2.0-dev.58: No such image: carldebilly/zigbee2mqttassistant:0.2.0-dev.58").

I am on a Rpi 3+ HassOS 2.12

**Comment by carldebilly** [comment]
I'm confused. This is supposed to work and I have friends for who it's working on HassOS + RP3.

May you retry? Maybe there was a problem on docker hub. Are you using a special version of HassOS? Do you have anyther special on your network which can prevent installations from docker hub?

**Comment by Costash67** [comment]
Thank you for replying.

**Comment by Costash67** [comment]
I do not have anything special on my network. I use HassOS 2.12 64 bit on a RPi 3B+ and i have some addons installed from the official hassio add-on store and also some customized (like Zigbee2Mqtt or DropboxSync from custom repositories).

**Comment by SalkinDK** [comment]
Getting the exact same error on the same setup here.
Can install all kinds of different add-ons but not this one.

`19-08-26 13:10:21 INFO (MainThread) [hassio.addons] Create Home Assistant add-on data folder /data/addons/data/806b11b5_zigbee2mqttassistant
19-08-26 13:10:22 INFO (SyncWorker_14) [hassio.docker.interface] Pull image carldebilly/zigbee2mqttassistant tag 0.2.0-dev.58.
19-08-26 13:10:26 ERROR (SyncWorker_14) [hassio.docker.interface] Can't install carldebilly/zigbee2mqttassistant:0.2.0-dev.58 -> 404 Client Error: Not Found ("no such image: carldebilly/zigbee2mqttassistant:0.2.0-dev.58: No such image: carldebilly/zigbee2mqttassistant:0.2.0-dev.58").
19-08-26 13:15:32 INFO (SyncWorker_16) [hassio.docker.interface] Pull image carldebilly/zigbee2mqttassistant tag 0.2.0-dev.58.
19-08-26 13:15:34 ERROR (SyncWorker_16) [hassio.docker.interface] Can't install carldebilly/zigbee2mqttassistant:0.2.0-dev.58 -> 404 Client Error: Not Found ("no such image: carldebilly/zigbee2mqttassistant:0.2.0-dev.58: No such image: carldebilly/zigbee2mqttassistant:0.2.0-dev.58").`

**Comment by thomaswr** [comment]
Same problem here with HASSOS 2.12 on raspberrypi3-64.

**Comment by raptr55** [comment]
same:

```
19-08-27 22:08:06 INFO (MainThread) [hassio.store] Load add-ons from store: 64 all - 1 new - 0 remove
19-08-27 22:08:11 INFO (SyncWorker_10) [hassio.docker.interface] Pull image carldebilly/zigbee2mqttassistant tag 0.2.0-dev.58.
19-08-27 22:08:13 ERROR (SyncWorker_10) [hassio.docker.interface] Can't install carldebilly/zigbee2mqttassistant:0.2.0-dev.58 -> 404 Client Error: Not Found ("no such image: carldebilly/zigbee2mqttassistant:0.2.0-dev.58: No such image: carldebilly/zigbee2mqttassistant:0.2.0-dev.58").
```

**Comment by carldebilly** [comment]
Which version of HASS_OS did you install?  32 bits ot 64 bits?

**Comment by Costash67** [comment]
The problem is on 64 bits. I installed the 32 bits of Hass_OS (Hassio) on a new RPi 4 and it worked. Thank you for this great add-on! I will stick to 32 bits :)

**Comment by raptr55** [comment]
Not sure... 64 bits

**Comment by SalkinDK** [comment]
> Which version of HASS_OS did you install? 32 bits ot 64 bits?

I am on 64 bits

**Comment by carldebilly** [comment]
Ok.  Looks like there's a problem with the "ARMv8" image on docker hub. I was under the impression the ARMv7 version would be picked automatically by the docker client. I'll make few test and I'll publish a "ARMv8 - 64 bits" image in few days. Will probably be based on "alpine" instead of "stretch-slim".

**Comment by carldebilly** [comment]
@SalkinDK @raptr55 @Costash67 Please try again, I pushed a new tag in the docker manifest to target "arm64" systems.

Please tell me if it works for you or if you're getting another error.

**Comment by raptr55** [comment]
still same error:

`19-09-07 16:52:20 INFO (SyncWorker_2) [hassio.docker.interface] Pull image carldebilly/zigbee2mqttassistant tag 0.2.0-dev.66.
19-09-07 16:52:23 ERROR (SyncWorker_2) [hassio.docker.interface] Can't install carldebilly/zigbee2mqttassistant:0.2.0-dev.66 -> 404 Client Error: Not Found ("no such image: carldebilly/zigbee2mqttassistant:0.2.0-dev.66: No such image: carldebilly/zigbee2mqttassistant:0.2.0-dev.66").`

**Comment by SalkinDK** [comment]
@carldebilly 
Still the same.
`19-09-09 18:27:42 INFO (SyncWorker_13) [hassio.docker.interface] Pull image carldebilly/zigbee2mqttassistant tag 0.2.0-dev.66.
19-09-09 18:27:44 ERROR (SyncWorker_13) [hassio.docker.interface] Can't install carldebilly/zigbee2mqttassistant:0.2.0-dev.66 -> 404 Client Error: Not Found ("no such image: carldebilly/zigbee2mqttassistant:0.2.0-dev.66: No such image: carldebilly/zigbee2mqttassistant:0.2.0-dev.66").
`

**Comment by thomaswr** [comment]
Works on my setup now, thank you!

**Comment by watson387** [comment]
I was having the same issue.  Works now after the update.  Thanks!

**Comment by SalkinDK** [comment]
> Yesterday I published another add-on just for the aarch64 platform. Please try it.

Just installed the new 64bit version and everything is working now.
Thank you for your work

**Comment by Costash67** [comment]
So we can close this. Thank you very much for your work!

**Comment by carldebilly** [comment]
@Costash67 @SalkinDK @watson387 @thomaswr @raptr55 
Hey guys!  please try again with latest version, it should work now ;-)
