### ISSUE TITLE
device pictures from zigbee2mqtt

### ISSUE THREAD

**Issue by remb0** [yllibed/Zigbee2MqttAssistant#53]
It's not a bug but a feature request.

is it possible to show a device picture like: https://gist.github.com/mhelff/1f1c0dde4ff193e5c14d5b99442a7d00 

it uses: icon': 'https://www.zigbee2mqtt.io/images/devices/' + entry.model.replace(new RegExp('/', 'g'), '-') + '.jpg'\n      }

But it's very have to see a picture instead of a gui/number to recognise the devices.

**Comment by carldebilly** [comment]
That is an AWESOME idea!!
![](https://media.giphy.com/media/d2Z9QYzA2aidiWn6/giphy.gif)

**Comment by carldebilly** [comment]
@all-contributors please add remb0 to ideas

**Comment by remb0** [comment]
great news! It will boost the interface for sure :)

**Comment by CodeFinder2** [comment]
I would also be interested in this feature. Additionally I would recommend to also add a description / human readable name of every device, like in https://www.zigbee2mqtt.io/information/supported_devices.html

For example: instead of
"0x00124b0006227235
0x00124b0006227235
Bitron Home Router"

Something like

"0x00124b0006227235:
Bitron Video wireless socket (on/off, power measurement), AV2010/25

![logo](https://www.zigbee2mqtt.io/images/devices/AV2010-25.jpg) "

🙈

**Comment by carldebilly** [comment]
@remb0 
Implemented, available in the "dev" channel under version `0.3.125`.  Please test it!

**Comment by CodeFinder2** [comment]
I just tested this! 😊 Thank you so much, beautiful!

Suggestions/improvements:
- What about creating a link on every image to the respective device info page of Z2M? E.g., to https://www.zigbee2mqtt.io/devices/SPZB0001.html for the thermostat. 

- I still have some devices with the fallback image ("wifi icon") although the devices seem to be detected / configured correctly in Z2M (although they are offline but that shouldn't matter). Is this a bug? The images are present in the device wiki pages of Z2M. What information/device state is used/required to grab the image successfully? Here's an exemplary screenshot:
![Screenshot_20200110-113049](https://user-images.githubusercontent.com/20599588/72146442-bb638e00-339c-11ea-8354-8d58e7f6cc77.jpg)
In total 5 images (2 Bitron plugs 902010/25, Innr sp120 plug, 2 Ikea tradfi remotes) are missing in my setup.
- What about caching the images so that they are available offline (once cached)? 
- Would it be possible to specify a custom image for the coordinator (since I guess it will always be the fallback image)? And a lot of people are using a customized version (eg. CC2530 / CC1352P-2, like me). 🙈

**Comment by carldebilly** [comment]
@CodeFinder2 
I just pushed another update: https://github.com/yllibed/Zigbee2MqttAssistant/pull/158

It's resolving some images were not displaying correctly + an image for the coordinator.

You have wonderful ideas and I would be happy to accept & merge any change improving this. I thought about the caching, but since it's not very critical, it's not a big problem to just have default images when you have no internet connection.

If you want to convert all images to PNG, sure, it would be a nice idea to talk to @Koenkk about this, as it should be done on its side.

**Comment by carldebilly** [comment]
@all-contributors please add codefinder2 to ideas

**Comment by CodeFinder2** [comment]
@carldebilly Thanks for the update. There's now only one image left that is not resolved correctly: the [Innr SP 120 smart plug](https://www.zigbee2mqtt.io/devices/SP_120.html). Z2MA reports `Model is 'SP 120' by innr'`.

If I have time, I'll take a look to see if I can add more features according to my suggestions above. Thanks for considering them, glad that you would be fine with them! :-)

**Comment by carldebilly** [comment]
Ok there's a space in the name...  https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L2596

Let me check this.

**Comment by carldebilly** [comment]
@CodeFinder2 Should work now.

**Comment by CodeFinder2** [comment]
> @CodeFinder2 Should work now.

Unfortunately, still not working (v0.3.129):
![Screenshot_20200113-200500__01](https://user-images.githubusercontent.com/20599588/72284128-87a89280-3640-11ea-80de-76005002653e.jpg)


(In the wiki, the space is replaced (in the URL) with a `-`
https://www.zigbee2mqtt.io/images/devices/SP-120.jpg )

**Comment by carldebilly** [comment]
ARGHHH.  Ok ;-)

**Comment by CodeFinder2** [comment]
Now it's working, great! 🙂

**Comment by CodeFinder2** [comment]
Just realized that the column titles are not correctly aligned or am I wrong here? :see_no_evil:

I assume they all need to be moved to right.

**Comment by carldebilly** [comment]
That's the bootstrap framework default... there's absolutely no change to it. I should find a skin... but that would be another issue :-)
May we close this one?

**Comment by CodeFinder2** [comment]
Yes, sure! Thanks again for all your efforts! :-)

**Comment by ellnic** [comment]
@carldebilly Not sure if this is worth a fresh issue, but would it be possible to add the ability to use a user specified custom image? I am just about to hack together a light using LEDs but the image won't be a ceiling light, obviously.

**Comment by carldebilly** [comment]
@ellnic Yes you should create a new issue for this.

**Comment by ellnic** [comment]
Thanks, done! #258
