### ISSUE TITLE
MQTT Server Port

### ISSUE THREAD

**Issue by seaverd** [yllibed/Zigbee2MqttAssistant#58]
Would it be possible to create an environmental variable for the MQTT Server Port?  I tried passing 192.168.0.50:11883 as I use a non-standard port and am unable to connect to my existing mqtt server.  In other dockers I have had to send the mqtt server and the mqtt port as two separate variables.  

Thanks for your consideration
Dan

**Comment by carldebilly** [comment]
It's already there... you can specify any of the settings using environment variables...

Here's the documentation: <https://github.com/yllibed/Zigbee2MqttAssistant#settings>

For the port, the environment variable will be:
```
Z2MA_SETTINGS__MQTTPORT=11883
```

Feel free to reopen this issue if the problem persists.

**Comment by seaverd** [comment]
OK, I have the port set....now I get this in my logs:

[40m [1m [33mwarn [39m [22m [49m:
Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
No XML encryptor configured. Key {ea0bd57d-63d2-48ba-bc19-91e760bf1da8} may
be persisted to storage in unencrypted form.
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.

Any suggestions?

Thanks,
Dan

**Comment by carldebilly** [comment]
This will appear the first time you start the container.  You can ignore this warning.

**Comment by seaverd** [comment]
Ok...just updated docker and get the following:

[41m[30mfail[39m[22m[49m:
Zigbee2MqttAssistant.Services.MqttConnectionService[0]
Error processing MQTT message on topic 'zigbee2mqtt/bridge/config/devices'
Newtonsoft.Json.JsonReaderException: Error reading JArray from JsonReader.
Current JsonReader item is not an array: Integer. Path '', line 1, position
13.

**Comment by carldebilly** [comment]
Which version of Zigbee2Mqtt are you using to get this error?

Are you able to capture the content of this topic using a tool like MqttExplorer?

**Comment by seaverd** [comment]
Zigbee2mqtt version is 1.60

When I go to:
zigbee2mqtt/bridge/config/devices  there is a single value posted every
couple of seconds....which looks like an epoch time stamp...here is a
sample value:  1570663123081
Not sure about scaling...if you divide that number by 1000 and enter it
into an epoch time converter you get exactly current time.

Should it be mapped to: zigbee2mqtt/bridge/log   ...because I then get a
value like below:
{"type":"devices","message":[{"ieeeAddr":"0x00124b0019365b53","type":"Coordinator"},{"ieeeAddr":"0x00158d000205b9e1","type":"EndDevice","model":"WXKG11LM","friendly_name":"BedroomButton","nwkAddr":25653,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_switch.aq2"},{"ieeeAddr":"0x00158d0002ec2f8c","type":"EndDevice","model":"RTCGQ11LM","friendly_name":"DiningRoomMotion","nwkAddr":61206,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_motion.aq2"},{"ieeeAddr":"0x00158d0002672827","type":"EndDevice","model":"RTCGQ01LM","friendly_name":"LiliasRoomMotion","nwkAddr":62234,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_motion"},{"ieeeAddr":"0x00158d000257a9cf","type":"EndDevice","model":"RTCGQ11LM","friendly_name":"KitchenMotion","nwkAddr":62952,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_motion.aq2","hwVersion":1,"swBuildId":"3000-0001","dateCode":"20170627"},{"ieeeAddr":"0x00158d0002ec048d","type":"EndDevice","model":"RTCGQ11LM","friendly_name":"BedroomMotion","nwkAddr":38310,"manufId":4151,"modelId":"lumi.sensor_motion.aq2"},{"ieeeAddr":"0x00158d0002ea6fa0","type":"EndDevice","model":"RTCGQ11LM","friendly_name":"LivingroomMotion","nwkAddr":26294,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_motion.aq2","hwVersion":1,"swBuildId":"3000-0001","dateCode":"20170627"},{"ieeeAddr":"0xd0cf5efffe04e487","type":"Router","model":"LED1624G9","friendly_name":"HallLight","nwkAddr":51041,"manufId":4476,"manufName":"IKEA
of Sweden","powerSource":"Mains (single phase)","modelId":"TRADFRI bulb E26
CWS opal
600lm","hwVersion":1,"swBuildId":"1.3.002","dateCode":"20170315"},{"ieeeAddr":"0x000d6ffffeac2397","type":"Router","model":"E1603/E1702","friendly_name":"0x000d6ffffeac2397","nwkAddr":24675,"manufId":4476,"manufName":"IKEA
of Sweden","powerSource":"Mains (single phase)","modelId":"TRADFRI control
outlet","hwVersion":1,"swBuildId":"1.4.020","dateCode":"20180528"},{"ieeeAddr":"0x000d6ffffe78a747","type":"Router","model":"E1603/E1702","friendly_name":"0x000d6ffffe78a747","nwkAddr":63218,"manufId":4476,"manufName":"IKEA
of Sweden","powerSource":"Mains (single phase)","modelId":"TRADFRI control
outlet","hwVersion":1,"swBuildId":"1.4.020","dateCode":"20180528"},{"ieeeAddr":"0x00158d000267270a","type":"EndDevice","model":"RTCGQ01LM","friendly_name":"BasementMotion1","nwkAddr":18051,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_motion","hwVersion":2,"swBuildId":"3000-0001","dateCode":"20160524"},{"ieeeAddr":"0x00158d0002563e69","type":"EndDevice","model":"RTCGQ01LM","friendly_name":"BasementMotion2","nwkAddr":32163,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_motion"},{"ieeeAddr":"0x00158d00026726cd","type":"EndDevice","model":"RTCGQ01LM","friendly_name":"BasementMotion3","nwkAddr":47124,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_motion"},{"ieeeAddr":"0x00158d00028834b7","type":"EndDevice","model":"SJCGQ11LM","friendly_name":"FurnaceLeak","nwkAddr":32780,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_wleak.aq1","hwVersion":2,"swBuildId":"3000-0001","dateCode":"20170721"},{"ieeeAddr":"0x00158d000281f5f5","type":"EndDevice","model":"SJCGQ11LM","friendly_name":"BasementLeak","nwkAddr":43750,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_wleak.aq1","hwVersion":2,"swBuildId":"3000-0001","dateCode":"20170721"}]}

**Comment by carldebilly** [comment]
Oooh the format of the content is different than usual. Are you on "edge" or "stable" version of Zigbee2Mqtt?

**Comment by carldebilly** [comment]
Ok I see the problem.  It seems there's a new format.  Let me fix this.

**Comment by carldebilly** [comment]
@all-contributors please add seaverd to bugs

**Comment by carldebilly** [comment]
Fixed

**Comment by seaverd** [comment]
FYI,

This still isn't working for me.   Here is what I get in the logs...I still
think something is wrong with the MQTT topic as the path in the log entry
below is just a timestamp,  the actual devices are in this topic:
zigbee2mqtt/bridge/log:

Thanks,

Dan

 Zigbee2MqttAssistant.Services.MqttConnectionService[0]
Error processing MQTT message on topic 'zigbee2mqtt/bridge/config/devices'
System.ArgumentOutOfRangeException: Index and length must refer to a
location within the string.
Parameter name: length
at System.String.Substring(Int32 startIndex, Int32 length)
at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevices(String
payload) in
d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 322
at
Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchDevicesMessage(MqttApplicationMessage
msg) in
d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 357
at
Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs
eventArgs) in
d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 217
